variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  BUILD_IMAGE: $INTERNAL_DOCKER_REGISTRY/$INTERNAL_IMAGE_NAME

# Variables used from the "Outside"
# INTERNAL_DOCKER_REGISTRY
# INTERNAL_IMAGE_NAME
# DEPENDENCYTRACK_URL
# DEPENDENCYTRACK_TOKEN

stages:
  - check
  - build
  - deploy

java dependencies:
  stage: check
  image: $BUILD_IMAGE
  script:
    - mvn $MAVEN_CLI_OPTS
      org.cyclonedx:cyclonedx-maven-plugin:2.7.9:makeAggregateBom
    - mvn $MAVEN_CLI_OPTS
      io.github.pmckeown:dependency-track-maven-plugin:1.6.0:upload-bom
      -Ddependency-track.dependencyTrackBaseUrl="$DEPENDENCYTRACK_URL"
      -Ddependency-track.apiKey="$DEPENDENCYTRACK_TOKEN"
    - mvn $MAVEN_CLI_OPTS
      io.github.pmckeown:dependency-track-maven-plugin:1.6.0:metrics
      -Ddependency-track.dependencyTrackBaseUrl="$DEPENDENCYTRACK_URL"
      -Ddependency-track.apiKey="$DEPENDENCYTRACK_TOKEN"
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev-main"
    
check unittests:
  stage: check
  image: $BUILD_IMAGE
  script:
    - mvn $MAVEN_CLI_OPTS clean test
  artifacts:
    when: always
    paths:
      - "*/*/target/surefire-reports/TEST-*.xml"
    reports:
      junit: "*/*/target/surefire-reports/TEST-*.xml"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev-main"

build:
  image: $BUILD_IMAGE
  stage: build
  script: 
    - mvn $MAVEN_CLI_OPTS install -DskipTests

job deploy:
  image: $BUILD_IMAGE
  stage: deploy
  variables:
    DISTRIBUTION_ID: $MAVEN_DISTRIBUTION_ID
    DISTRIBUTION_URL: $INTERNAL_MAVEN_REPOSITORY
    DISTRIBUTION_SNAPSHOT_ID: $MAVEN_DISTRIBUTION_ID
    DISTRIBUTION_SNAPSHOT_URL: $INTERNAL_MAVEN_SNAPSHOT_REPOSITORY
  script:
    - mvn deploy -DskipTests
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "main"

job deploy snapshot:
  image: $BUILD_IMAGE
  stage: deploy
  variables:
    DISTRIBUTION_ID: $MAVEN_DISTRIBUTION_ID
    DISTRIBUTION_URL: $INTERNAL_MAVEN_REPOSITORY
    DISTRIBUTION_SNAPSHOT_ID: $MAVEN_DISTRIBUTION_ID
    DISTRIBUTION_SNAPSHOT_URL: $INTERNAL_MAVEN_SNAPSHOT_REPOSITORY
  script:
    - mvn deploy -DskipTests
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "dev-main"

job deploy maven central:
  image: $BUILD_IMAGE
  stage: deploy
  variables:
    DISTRIBUTION_ID: ossrh
    DISTRIBUTION_URL: $MAVEN_CENTRAL_REPOSITORY_URL
  script:
    - echo $PGP_RELEASE_SIGNING_KEY | base64 -d > releases@kgs-software.com.signing-subkey.asc
    - gpg --import releases@kgs-software.com.signing-subkey.asc
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "main"



