name: Release packages to GitHub Packages
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - 'main'
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          # server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          # settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Publish package
        run: mvn --batch-mode deploy # -s $GITHUB_WORKSPACE/settings.xml
        env:
          # GHCR_TOKEN - appears confusing here, but this is how we called it elsewhere
          # GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
          DISTRIBUTION_ID: github
          DISTRIBUTION_URL: https://maven.pkg.github.com/deas/chemistry-opencmis
          # DISTRIBUTION_SNAPSHOT_ID:
          # DISTRIBUTION_SNAPSHOT_URL:
